version: '3'

services:

  mariadb:
    image: mariadb:10.3.9
    container_name: ${APP_NAME:?err}-mariadb
    ports:
      - '3306:3306'
    restart: 'on-failure'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    volumes:
      - ${PWD}
      - '../schema:/tmp/schema'

  # go:
  #   container_name: ${APP_NAME:?err}-go
  #   build:
  #     context: ./
  #     dockerfile: go.Dockerfile
  #   volumes:
  #     - "..:/go/src/housemates"
  #   working_dir: "/go/src/housemates"
  #   command: go run main.go